export enum BlockchainErrorCode {
  UNKNOWN = 'UNKNOWN',
  TIMEOUT = 'TIMEOUT',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  INVALID_PARAMS = 'INVALID_PARAMS',
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  METHOD_NOT_FOUND = 'METHOD_NOT_FOUND',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',
  RETRY_EXCEEDED = 'RETRY_EXCEEDED',
  // Add more as needed
}
